sharedSecret: <created-with-`pwgen 128 -n 1`>
serviceProviders:
- type: GitHub
  clientId: <client-id-from-github-app>
  clientSecret: <client-secret-from-github-app>
baseUrl: https://github.com/login/oauth/authorize
